#!/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2017 Kogo Software LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

scriptName="$(basename $0)"
source `which ngx-helpers`

export `grep 'ngx_module_name=' src/config`

assertNgxVersion
assertModuleName

tmpDir="/tmp/$projectName"
if [[ -d "$tmpDir" ]]; then
  rm -rf "$tmpDir"
fi
mkdir -p "$tmpDir"
cp $NGX_TEST_SRCS "$tmpDir"

cat > "$tmpDir/Dockerfile" <<~
FROM nginx:$NGX_VERSION

ADD nginx.conf /etc/nginx/nginx.conf
ADD ${ngx_module_name}.so /etc/nginx/modules/${ngx_module_name}.so
$NGX_ADDTL_DOCKER_DIRECTIVES
~

testContainerName="$projectName-test"
docker build -t "$testContainerName" "$tmpDir"
docker rm -f "$testContainerName" || true
docker run -d -p 80:80 --name "$testContainerName" "$testContainerName"

logScriptComplete
