#!/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2017 Kogo Software LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

projectName="$(basename $PWD)"
cleanIncludes=''
includesDir=./include
libsDir=./libs
NGX_VERSION=''
code_bold="\x1b[1m"
code_dim="\x1b[2m"
code_green="\x1b[32m"
code_red="\x1b[31m"
code_reset_all="\x1b[0m"
code_terminal_reset="\033c"
code_underlined="\x1b[4m"

function error {
  echo "$scriptName: $1" >&2
}

function assertTruthy() {
  if [[ -z "$2" ]]; then
    error "$1 was empty!"
    exit 1
  fi
}

function assertModuleName() {
  if [[ -z "$ngx_module_name" ]]; then
    error "ngx_module_name was empty in module config"
    exit 1
  fi
}

function assertNginxLibSrc() {
  if [[ ! -L libs/nginx-src ]]; then
    error "Expected to see libs/nginx-src.  Have you run ngx-add-source-to-project?"
    exit 1
  fi
}

function assertNgxVersion() {
  if [[ -z "$NGX_VERSION" ]]; then
    error "NGX_VERSION was empty!  Set it in .ngxrc or supply --nginx-version"
    exit 1
  fi
}

function logScriptComplete() {
  echo -e "$scriptName: ${code_bold}done${code_reset_all}"
}

if [[ -f .ngxrc ]]; then
  source .ngxrc
fi

while [ "$#" != '0' ];do
  case "$1" in
    -h|--help)
      help
      exit;;
    --nginx-version)
      NGX_VERSION="$2"
      shift 2;;
    *)
      error "Unknown option $1"
      exit 1;;
  esac
done
